; ============================================================================
; TRANQI TRANSIT - CONFIGURACIÓN PLATFORMIO PARA VALIDADOR ESP32
; ============================================================================

[platformio]
src_dir = tranqi_validador_esp32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^6.21.4
    knolleary/PubSubClient@^2.8
